### ISSUE TITLE
请问何时能放出数据集？

### ISSUE THREAD

**Issue by Mainvooid** [Xiaoxianrou/SEENet#1]
以及当前模型能否适用不同分辨率，例如1080p？
谢谢

**Comment by andrewjywang** [comment]
正在整理数据集，稍后会放出。
我们是用128 * 128 训练的，由于网络结构有些复杂和硬件原因，升高分辨率可能会导致参数过多无法训练。如果你有硬件条件的话，我觉得是可以的。

**Comment by Mainvooid** [comment]
> 可以

请教一下，我目前有个任务是预测720P的下一帧，就一帧，有什么不太模糊，速度还快的方法么？找了一圈好像没啥好方法。

**Comment by andrewjywang** [comment]
> > 可以
> 
> 请教一下，我目前有个任务是预测720P的下一帧，就一帧，有什么不太模糊，速度还快的方法么？找了一圈好像没啥好方法。
你的任务跟我做的这个方向不是很一样。我建议你可以看一下[Dual Motion GAN](https://arxiv.org/pdf/1708.00284.pdf)这篇文章，我觉得他们的工作跟你的要求有些吻合。

**Comment by andrewjywang** [comment]
> 请教一下，我目前有个任务是预测720P的下一帧，就一帧，有什么不太模糊，速度还快的方法么？找了一圈好像没啥好方法。

你的任务跟我做的这个方向不是很一样。我建议你可以看一下Dual Motion GAN这篇文章，我觉得他们的工作跟你的要求有些吻合

**Comment by andrewjywang** [comment]
> 请教一下，我目前有个任务是预测720P的下一帧，就一帧，有什么不太模糊，速度还快的方法么？找了一圈好像没啥好方法。

你的任务跟我做的这个方向不是很一样。我建议你可以看一下[Dual Motion GAN](https://arxiv.org/abs/1708.00284)这篇文章，我觉得他们的工作跟你的要求有些吻合

**Comment by Mainvooid** [comment]
> > 请教一下，我目前有个任务是预测720P的下一帧，就一帧，有什么不太模糊，速度还快的方法么？找了一圈好像没啥好方法。
> 
> 你的任务跟我做的这个方向不是很一样。我建议你可以看一下[Dual Motion GAN](https://arxiv.org/abs/1708.00284)这篇文章，我觉得他们的工作跟你的要求有些吻合

谢谢，这篇也看过了。效果比较模糊，目前在测试[FutureGAN](https://github.com/TUM-LMF/FutureGAN)`这个模型。

关于视频预测，现在的模型基本上是在低分辨率训练集上训练的，而且很多效果比较模糊。
总体来说该问题领域理论缺乏，还在初步探索阶段，如果你是搞学术的有兴趣可以往这个方向研究一下，可能比较容易有突破。

**Comment by birdflyto** [comment]
> > > 请教一下，我目前有个任务是预测720P的下一帧，就一帧，有什么不太模糊，速度还快的方法么？找了一圈好像没啥好方法。
> > 
> > 
> > 你的任务跟我做的这个方向不是很一样。我建议你可以看一下[Dual Motion GAN](https://arxiv.org/abs/1708.00284)这篇文章，我觉得他们的工作跟你的要求有些吻合
> 
> 谢谢，这篇也看过了。效果比较模糊，目前在测试[FutureGAN](https://github.com/TUM-LMF/FutureGAN)`这个模型。
> 
> 关于视频预测，现在的模型基本上是在低分辨率训练集上训练的，而且很多效果比较模糊。
> 总体来说该问题领域理论缺乏，还在初步探索阶段，如果你是搞学术的有兴趣可以往这个方向研究一下，可能比较容易有突破。

你好，我感觉我的任务和你的比较相似，也是预测下一帧的图片，FutureGAN试了，效果不好，你还有其他试通了，效果还可以的模型吗

**Comment by andrewjywang** [comment]
> > > > 请教一下，我目前有个任务是预测720P的下一帧，就一帧，有什么不太模糊，速度还快的方法么？找了一圈好像没啥好方法。
> > > 
> > > 
> > > 你的任务跟我做的这个方向不是很一样。我建议你可以看一下[Dual Motion GAN](https://arxiv.org/abs/1708.00284)这篇文章，我觉得他们的工作跟你的要求有些吻合
> > 
> > 
> > 谢谢，这篇也看过了。效果比较模糊，目前在测试[FutureGAN](https://github.com/TUM-LMF/FutureGAN)`这个模型。
> > 关于视频预测，现在的模型基本上是在低分辨率训练集上训练的，而且很多效果比较模糊。
> > 总体来说该问题领域理论缺乏，还在初步探索阶段，如果你是搞学术的有兴趣可以往这个方向研究一下，可能比较容易有突破。
> 
> 你好，我感觉我的任务和你的比较相似，也是预测下一帧的图片，FutureGAN试了，效果不好，你还有其他试通了，效果还可以的模型吗

你好，我建议你先试试MCNet
