### ISSUE TITLE
The paper states that it uses the output of a trained PWCNet for the motion encoder but I cannot find in which part of the section of the source code PWCNet is mentioned. Please help!

### ISSUE THREAD

**Issue by gaurav-singh1998** [Xiaoxianrou/SEENet#3]

**Comment by andrewjywang** [comment]
Hi
I employed the pre-trained model from its [Official GitHub](https://github.com/NVlabs/PWC-Net)
Also, [SelfFlow](https://github.com/ppliuboy/SelFlow) can be used in this framework.

Hope this can help you.
